# Generated by Django 4.0.4 on 2022-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hostel_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
