# Generated by Django 4.0.4 on 2022-05-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0002_room_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Student',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
    ]
