# Generated by Django 4.0.4 on 2022-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0003_customuser_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerdetail',
            name='profilePic',
            field=models.ImageField(upload_to='ownerimage'),
        ),
    ]
