# Generated by Django 4.0.4 on 2022-05-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0004_alter_ownerdetail_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='images',
            field=models.ImageField(upload_to='hostelimage'),
        ),
    ]
