# Generated by Django 4.0.4 on 2022-05-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0005_alter_hostel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.hosteldetail'),
        ),
    ]
