# Generated by Django 4.0.4 on 2022-06-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0007_alter_hostel_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='details',
        ),
        migrations.AddField(
            model_name='hosteldetail',
            name='hostel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.hostel'),
            preserve_default=False,
        ),
    ]
