# Generated by Django 4.0.4 on 2022-06-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0008_remove_hostel_details_hosteldetail_hostel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldetail',
            name='hostel',
        ),
        migrations.AddField(
            model_name='hostel',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelmanagement.hosteldetail'),
        ),
    ]
