# Generated by Django 4.0.4 on 2022-06-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanagement', '0010_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='post',
            new_name='hostel',
        ),
    ]
